% Hypothetical Queries
% Source: [Bonn99], extended and adapted
% Coded by: F. Sáenz-Pérez
% Date: 1/15/2013

student(adam).
student(bob).
student(pete).
student(scott).
student(tony).

course(eng).
course(his).
course(lp).

take(adam,eng).
take(pete,his).
take(pete,eng).
take(scott,his).
take(scott,lp).
take(tony,his).

pre(eng,lp).
pre(hist,eng).
pre(Pre,Post) :-
  pre(Pre,X),
  pre(X,Post).

grad(S) :-
  take(S,his), 
  take(S,eng).

% :- pre(X,X).