a(a1).
a(a2).
a(a3).
a(a4).
b(a1).
b(b1).
b(b2).
c(a1,a1).
c(a1,b2).
c(a2,b2).
cartesian(X,Y) :-
  a(X),
  b(Y).
difference(X) :-
  a(X),
  not(b(X)).
full_join(X,Y) :-
  fj(a(X),b(Y),X = Y).
inner_join(X) :-
  a(X),
  b(X).
left_join(X,Y) :-
  lj(a(X),b(Y),X = Y).
projection(X) :-
  c(X,Y).
right_join(X,Y) :-
  rj(a(X),b(Y),X = Y).
selection(X) :-
  a(X),
  X = a2.
union(X) :-
  a(X)
  ;
  b(X).
